### ISSUE TITLE
pyro NullReferenceException creating patch

### ISSUE THREAD

**Issue by pfay** [wixtoolset/issues#5260]
Wix Version: 3.10.200.12804
OS: Windows 7 x64

Hi,

I am building a patch using melt & pyro as per Bob Arnson [post](https://www.joyofsetup.com/2013/07/16/easy-pure-wix-patching-with-melt/). My steps include,

melt old\v1.msi -out temp\older\v1.wixpdb -pdb old\v1.wixpdb -x temp\older\Source
melt new\v2.msi -out temp\newer\v2.wixpdb -pdb new\v2.wixpdb -x temp\newer\Source
torch -xi temp\older\v1.wixpdb temp\newer\v2.wixpdb -out temp\diff.wixmst
candle patch.wxs
light patch.wixobj -out temp\patch.wixmsp
pyro temp\patch.wixmsp -t RTM temp\diff.wixmst -out patch.msp 

However I keep getting a NullReferenceException from using pyro, 

pyro.exe : error PYRO0001 : Object reference not set to an instance of an object.
Exception Type: System.NullReferenceException

Stack Trace:
   at Microsoft.Tools.WindowsInstallerXml.Patch.BuildPairedTransform(String patchId, String clientPatchId, Output mainTransform, MediaRow mediaRow, Int32 validationFlags, String& productCode)
   at Microsoft.Tools.WindowsInstallerXml.Patch.AttachTransforms(ArrayList transforms)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Pyro.Run(String[] args)

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Tools.WindowsInstallerXml.Patch.BuildPairedTransform(String patchId, String clientPatchId, Output mainTransform, MediaRow mediaRow, Int32 validationFlags, String& productCode)
   at Microsoft.Tools.WindowsInstallerXml.Patch.AttachTransforms(ArrayList transforms)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Pyro.Run(String[] args)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Pyro.Main(String[] args)

Is this a known bug and if so can a fix be recommended?

Thank you

**Comment by barnson** [comment]
That's not a public build of WiX. For private WiX builds, you need to contact whoever provided it for support.

**Comment by pfay** [comment]
I get the exact same NullReferenceExcepion for public build 3.10.2.2516.

**Comment by barnson** [comment]
Please get the wix310-debug.zip and unzip the .pdbs next to wix.dll to get a detailed stack trace and send the details in a message to the wix-users mailing list.
