### ISSUE TITLE
OAWixProject.ConfigurationManager and UniqueName throw exception

### ISSUE THREAD

**Issue by NKnusperer** [wixtoolset/issues#5323]
## Bugs
- Which version of WiX are you building with?

> 3.10.2.2516
- Which version of Visual Studio are you building with (if any)?

> Visual Studio 2015 Update 2
- Which version of .NET are you building with?

> .NET 4.6.1
- Describe the problem and the steps to reproduce it.

> I'am the developer of a Visual Studio Extension called [BetterConfigurationManager](https://github.com/NKnusperer/BetterConfigurationManager) which allows bulk platform/configuration management for Visual Studio projects.
> Recently I got a bug report that my extension crashes when the solution contains a WiX setup project.
> After some debugging there seems to be two problems when a OAWixProject (EnvDTE.Project) is processed:
> 
> 1: When accessing [Project.UniqueName](https://msdn.microsoft.com/en-us/library/8bez2388.aspx):
> 
> ```
> System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    at Microsoft.VisualStudio.Package.Automation.OAProject.get_UniqueName()
> ```
> 
> 2: When accessing [Project.ConfigurationManager](https://msdn.microsoft.com/en-us/library/envdte.project.configurationmanager.aspx):
> 
> ```
> System.InvalidOperationException: Operation is not valid due to the current state of the object.
>    at Microsoft.VisualStudio.Package.Automation.OAProject.get_ConfigurationManager()
> ```
> 
> The code doing this is available here: [VisualStudioProject.cs](https://github.com/NKnusperer/BetterConfigurationManager/blob/master/ConfigurationManager/VisualStudioProject.cs)
- Describe the behavior you expected and how it differed from the actual behavior.

> To not throw an exception when accessing one of these two properties and return the proper UniqueName/ConfigurationManager.

**Comment by odalet** [comment]
For what it's worth, I had the very same issue (wix projects in my solution...), therefore, I fell back to using another similar extension: https://github.com/tom-englert/ProjectConfigurationManager 

Couldn't explain why, but using this other extension, I can handle my Wix projects... Examining this code may give you clues to fix this (without having to resort to the Wix team to fix their bug...)
