### ISSUE TITLE
Simplified Wix:  Improve error message when there is incorrect whitespace for a nested element

### ISSUE THREAD

**Issue by et13** [wixtoolset/issues#5388]
- Which version of WiX are you building with?

4.0.3922.0
- Which version of Visual Studio are you building with (if any)?

N/A - Using the command line tools (swc.exe)
- Which version of .NET are you building with?

4.6.01586
- Describe the problem and the steps to reproduce it.

Rename the attached file to example.swr (I could only attach it as .txt)
[example.txt](https://github.com/wixtoolset/issues/files/443206/example.txt)

Build the file: swc.exe -type wixlib -arch x86 example.swr

The file is malformed due to an extra tab for the nested folder:

folder name=InstallFolder:\
[tab]file "foo.txt" source="bin\foo.txt"
[tab][extra tab]folder name=f
[tab][tab]file "bar.txt" source="bin\bar.txt"

swc.exe outputs:

Unhandled Exception: System.ArgumentException: Object of type 'WixToolset.Simplified.Lexicon.Folder' cannot be converted to type 'WixToolset.Simplified.Lexicon.ITargetFile'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstanceType.AddChild(Object parent, Object child)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.InstantiateObject(List`1 items, String path, Dictionary`2 namespaces, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.Instantiate(List`1 items, String path, Dictionary`2 namespaces, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.InstantiateObject(List`1 items, String path, Dictionary`2 namespaces, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.Instantiate(List`1 items, String path, Dictionary`2 namespaces, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.InstantiateObject(List`1 items, String path, Dictionary`2 namespaces, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.Instantiate(List`1 items, String path, Dictionary`2 namespaces, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.ObjectInstantiator.Instantiate(String path, StatementNode node)
   at WixToolset.Simplified.CompilerFrontend.FrontendCompiler.InstantiateObjects(String path, StatementNode rootStatementNode)
   at WixToolset.Simplified.CompilerFrontend.FrontendCompiler.Parse(TextReader textReader, String path)
   at WixToolset.Simplified.CompilerFrontend.FrontendCompiler.Parse(String path)
   at WixToolset.Simplified.SimplifiedCompiler.CoreCompile(PackageArchitecture architecture, CultureInfo[] languages, String outputPath, Func`1 createBackendCompiler)
   at WixToolset.Simplified.SimplifiedWixCompiler.Run(Messaging messaging)
   at WixToolset.Simplified.SimplifiedWixCompiler.Main(String[] args)
- Describe the behavior you expected and how it differed from the actual behavior.

swc.exe should output an actionable error message (including the location of the error in the file) instead the unhandled exception message

**Comment by robmen** [comment]
swc is not being supported in v4. It's a future thing.

**Comment by robmen** [comment]
At this point swc is a v5 thing and it won't be integrated as swc.
