### ISSUE TITLE
UtilCompiler.cs setting Identifier to a row[]

### ISSUE THREAD

**Issue by nick2893** [wixtoolset/issues#5467]
Using Wix 4, September release; I'm trying to "candle" the following:

    <util:ProductSearch Variable="VCRedistx86Installed" ProductCode="{F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}" Result="state" />  
    <util:ProductSearch Variable="VCRedistx64Installed" ProductCode="{1D8E6291-B0D5-35EC-8441-6616F567A0F7}" Result="state" />  

And I get an error:

candle.exe : error CNDL0001 : Cannot set string column 'WixSearch_' with a value
 of type 'WixToolset.Extensibility.Identifier'.

Exception Type: System.InvalidOperationException

Stack Trace:
   at WixToolset.Data.ColumnDefinition.ValidateValue(Object value)
   at WixToolset.Data.Row.set_Item(Int32 field, Object value)
   at WixToolset.Extensions.UtilCompiler.ParseProductSearchElement(XElement node
)
   at WixToolset.Extensions.UtilCompiler.ParsePossibleKeyPathElement(XElement pa
rentElement, XElement element, IDictionary`2 context)
   at WixToolset.Extensions.UtilCompiler.ParseElement(XElement parentElement, XE
lement element, IDictionary`2 context)
   at WixToolset.CompilerCore.ParseExtensionElement(XElement parentElement, XEle
ment element, IDictionary`2 context)
   at WixToolset.Compiler.ParseBundleElement(XElement node)
   at WixToolset.Compiler.ParseWixElement(XElement node)
   at WixToolset.Compiler.Compile(XDocument source)
   at WixToolset.Tools.Candle.Run()
   at WixToolset.Tools.Candle.Execute(String[] args)

I believe in UtilCompiler.cs, in private void ParseProductSearchElement(XElement node), the following line:

row[0] = id;

Should be:

row[0] = id.Id;

(similar code appears in multiple places)

**Comment by lehne** [comment]
Has this been released yet? If not, is there a workaround? I'm running into this with 4.0.0.5205.

**Comment by SwooshyCueb** [comment]
I've opened a pull request back in may to address the issue, but it hasn't been merged yet.

**Comment by robmen** [comment]
WiX v4 is getting a major [repository reorganization](http://wixtoolset.org/development/wips/5489-repository-reorganization/). I _believe_ this issue was fixed in the Util.wixext repo already. I left the PR open to ensure I double check and then resolve this issue.

Note: WiX v4 is under massive development so there is still lots of change to come.
