### ISSUE TITLE
VS 2017 Build Tools + Wix Project build

### ISSUE THREAD

**Issue by PavelA85** [wixtoolset/issues#5525]
I have build environment.
I installed Build Tools for Visual Studio 2017 from https://www.visualstudio.com/downloads/
Installed WiX v3.11 (RC) from http://wixtoolset.org/releases/
When I build project on remote I get error:

`System.Exception: An exception was thrown in the remote environment: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> nCrunch.Common.UserException: Errors occurred while trying to load the project file: 
The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\..\WiX Toolset v3.11\bin\WixTasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\WiX Toolset v3.11\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
   at nCrunch.Compiler.RemoteBuildRunner.(FilePath , LoadTimeQuery , String , String , DirectoryPath , String )
   at nCrunch.Compiler.RemoteBuildRunner.AnalyseComponentBuild(ComponentLoadParameters parameters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at nCrunch.TaskRunner.Ipc.IpcMessageProcessor.(CallMethodMessage )
   at nCrunch.TaskRunner.Ipc.IpcMessageProcessor.ProcessMessageReturningResult(Byte[] data)
   at nCrunch.TaskRunner.Ipc.RemoteInstance.(Byte[] )
   at nCrunch.TaskRunner.Ipc.RemoteInstance.Invoke(IMessage msg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at nCrunch.Compiler.IRemoteBuildRunner.AnalyseComponentBuild(ComponentLoadParameters parameters)
   at nCrunch.Core.BuildManagement.BuildProcessLauncher..(IRemoteBuildRunner )
   at nCrunch.Core.BuildManagement.BuildProcessLauncher.(Action`1 , FilePath , String , ExternalProcess )
   at nCrunch.Core.BuildManagement.BuildProcessLauncher.(Action`1 , ProcessorArchitecture , GridClientId , BuildSystemParameters , IList`1 )
   at nCrunch.Core.BuildManagement.BuildProcessLauncher.AnalyseComponentBuildInExternalProcess(ComponentLoadParameters parameters, IList`1 customEnvironmentVariables)
   at nCrunch.Client.ComponentLoader.SnapshotComponentFactory.(ProcessorArchitecture )
   at nCrunch.Client.ComponentLoader.SnapshotComponentFactory.CreateSnapshotComponentFromXml(FilePath projectFilePath, BuildXml projectXml, FilePath solutionFilePath, String[] additionalFilesToIncludeAtSolutionLevel, Boolean isLoadedFromFile, VisualStudioVersion vsVersion)
`

On my machine VS2017 + Wix Tools works as expected.

How can I build Wix 3 project on my build machine?

**Comment by PavelA85** [comment]
I was wrong stating that my local machine builds Wix project.
It fails with same error.
Error was gone after copying `WiX Toolset v3.11` folder from `C:\Program Files (x86)` to `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise`

**Comment by jcmcbeth** [comment]
I also have this issue with v3.10, except the error is:

`The "ReadRegistry" task could not be loaded from the assembly D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll. Could not load file or assembly 'file:///D:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.`

This project was working prior to upgrading to Visual Studio 2017. There is no WiX Toolset v3.10 folder at the path that it is looking for.

My issue was also fixed when I copied the WiX Toolset v3.10 folder from C:\Program Files (X86) to the directory it was looking for.

**Comment by robmen** [comment]
Unfortunately, MSBuild15 (now part of VS2017) broke backward compatibility (more details here: Microsoft/msbuild#832).

You can install the WiX Toolset Visual Studio 2017 Extension to get our workaround for the MSBuild15 break. Unfortunately, that can only add support in VS2017 itself.

To support the Build SKU, you'll need to install WiX v3.11 RC2 *and* apply the same changes we made to the project templates. You can see those changes here: https://github.com/wixtoolset/VisualStudioExtension/pull/4/files#diff-a326b4bfbbe9f0c6cf43f75b8034179b

The important part of those changes are to remove the Property definition `WixCATargetsPath` and change the Imports to:

    <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
    <Import Project="$(WixCATargetsPath)" Condition=" '$(WixCATargetsPath)' != '' " />
    <Import Project="$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.CA.targets" Condition=" '$(WixCATargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.CA.targets') " />

Again, you will need WiX v3.11 RC2 as well as these changes.

**Comment by joaocgreis** [comment]
Details link above should probably be https://github.com/Microsoft/msbuild/issues/1832 (832 -> 1832). Thanks for your work on this @robmen!

**Comment by pateljeel** [comment]
Where can I find the download for WiX 3.11 RC2?
