### ISSUE TITLE
The argument 'project' is null at at Microsoft.Tools.WindowsInstallerXml.VisualStudio.WixHelperMethods.TraceFail(String message, Object[] args)

### ISSUE THREAD

**Issue by hkyupelyan** [wixtoolset/issues#5544]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
I am using WiX Toolset v3.10.3
> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?
I am building with Visual Studio 2015 Professional Edition with Updates Version  14.0.25431.01 Update 3
> (Visual Studio version, including year and update)

* Which version of .NET are you building with?
4.6.010.55
> (.NET version)

Wix 2015 Visual studio extension version: 
WiX Toolset Visual Studio Extension version 0.9.10.21458

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
Windows server 2012 R2 Standard x64
* Describe the problem and the steps to reproduce it.
1) Step 1 Create a Wix V3 Setup Project.
2) Once the project is created and loaded, right click on the project and go to properties.
3) Next click on the 'tool settings' navigation on the left and you will get the following error message in the popup dialog box with with abort, retry ignore buttons on the buttom :

---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
The argument 'project' is null.

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.WixHelperMethods.TraceFail(String message, Object[] args)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.WixHelperMethods.VerifyNonNullArgument(Object argument, String argumentName)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.ProjectProperty..ctor(WixProjectNode project, String propertyName)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.PropertyPages.WixPropertyPage.GetProperty(String propertyName)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.PropertyPages.WixPropertyPagePanel.BindProperties(Control control)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.PropertyPages.WixPropertyPagePanel.BindProperties(Control control)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.PropertyPages.WixPropertyPagePanel.BindProperties(Control control)

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.PropertyPages.WixToolsSettingsPropertyPagePanel.BindProperties()

   at Microsoft.Tools.WindowsInstallerXml.VisualStudio.PropertyPages.WixPropertyPage.Microsoft.VisualStudio.OLE.Interop.IPropertyPage.Activate(IntPtr hwndParent, RECT[] rects, Int32 modal)

   at Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.ActivatePage(IPropertyPage PropPage)

   at Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.Init(Project DTEProject, IPropertyPage PropPage, PropertyPageSite PropPageSite, IVsHierarchy Hierarchy, Boolean IsConfigPage)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.ShowTab(Int32 Index, Boolean ForceShow)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.OnInitializationComplete()

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.PopulateView(Guid guidLogicalView)

   at Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerWindowPane.ActivateLogicalView(Guid& rguidLogicalView)

   at Microsoft.VisualStudio.Shell.Interop.IVsProject2.ReopenItem(UInt32 itemid, Guid& rguidEditorType, String pszPhysicalView, Guid& rguidLogicalView, IntPtr punkDocDataExisting, IVsWindowFrame& ppWindowFrame)

   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.ReopenDocumentFrame(WindowManagerService windowManager, StubWindowInfo stubInfo, ReopenDocumentOptions options, DocumentGroup docGroup, Int32& hr)

   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.ReopenDocumentFrame(IWindowManagerPrivate windowManager, StubWindowInfo stubInfo, ReopenDocumentOptions options, DocumentGroup docGroup, Int32& hr)

   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.ReopenDocumentFrame(IWindowManagerPrivate windowManager, StubWindowInfo stubInfo, ReopenDocumentOptions options, DocumentGroup docGroup)

   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.<>c__DisplayClass22_0.<LoadBinaryDocumentStates>b__0(VersionedBinaryReader VersionedBinaryReader)

   at Microsoft.VisualStudio.Utilities.VersionedBinaryReader.ReadVersioned(Int32 expectedVersion, ReadCallback callback, Boolean throwOnUnexpectedVersion)

   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.LoadBinaryDocumentStates(WindowManagerService windowManager, IStream comStream, Boolean isExternal)

   at Microsoft.VisualStudio.Platform.WindowManagement.SolutionOptions.LoadDocumentStates(WindowManagerService windowManager, IStream comStream, Boolean isExternal)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.<>c__DisplayClass174_0.<LoadDocumentStates>b__0()

   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Action method, Boolean reportError)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.LoadDocumentStates(IStream stream, Int32 fExternal)

---------------------------
Abort   Retry   Ignore   
---------------------------
![wix_error](https://cloud.githubusercontent.com/assets/26240790/24260148/42a8fc7e-0fb0-11e7-983a-6e112de3d4ac.jpg)

Please see the attached error as well. It looks like the WiX Toolset 2015 Visual Studio Extension version 0.9.10.21458 is unable to properly do the reflection and cannot get the project name.
Please let me know how to address this. My email is hkyupelyan@hotmail.com

Regards,
Harry Kyupelyan
harry.kyupelyan@hotmail.com

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by hkyupelyan** [comment]
A small update, my version of .net framework I am using is 4.5.2 and not 4.6.010.55 as previously stated.
Regards,
Harry

**Comment by barnson** [comment]
WiX v3.10.3 comes with the VS extension so installing one from the Marketplace might be problematic. Try removing the extension.

**Comment by hkyupelyan** [comment]
Dear Barson,

Did not realize that Wix V3.10.3 had built in extensions. That also explains why I was getting duplicate entries when I was trying to create a wix project. The market place extension has been removed and problem no longer exists. Thanks for quick response Barson.
Regards,
Harry

**Comment by hkyupelyan** [comment]
As a side note, it might make sense to also explicitly state that that if you download wix V3.10.3 or higher, you no longer need to download the WiX Toolset Visual Studio 2015 Extension explicitly. As of now, the the Wix's official website http://wixtoolset.org/releases/ still states that the extensions need to be downloaded from the market place and in fact it also provides a link to it: https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2015Extension

Regards,
Harry

**Comment by barnson** [comment]
The extension is separate starting with WiX v3.11.

**Comment by hkyupelyan** [comment]
Dear Bob,
Thanks for clear explanation and your time.
Regards,
Harry
