### ISSUE TITLE
Wix Toolset Visual Studio 2017 Extension dows not install with the Visual Studio Build tools 2017

### ISSUE THREAD

**Issue by BartHuls** [wixtoolset/issues#5573]
On the Build server  I installed the Visual Studio Build Tools for 2017 (mu_build_tools_for_visual_studio_2017_version_15.1_x86_x64_10331420)

I installed the Wix311 toolset  and tried to install the Wix Toolset Visual Studio 2017 Extension 

I get during installation:
4-5-2017 10:33:27 - Found installed product - Visual Studio Build Tools 2017
4-5-2017 10:33:27 - System.IO.FileNotFoundException: C:\Program Files (x86)\Microsoft Visual Studio\2017\
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by barnson** [comment]
VSIXInstaller is part of Visual Studio; we don't have control over it. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

**Comment by robmen** [comment]
As far as we know, Visual Studio doesn't support installing Extensions on the Build Tools. This is a gap in their design.

The work around is to update your .wixproj to the "new" way that supports VS Build Tools.  Until we get more documentation up, easiest way would be to create a new WiX project with the new WiX VS Extension and look at how the project differs from your current project (particularly around the `Imports`).
