### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object. when installing wix vs 2013 extension

### ISSUE THREAD

**Issue by omrivm** [wixtoolset/issues#5756]
* Which version of WiX are you building with?
3.11

* Which version of Visual Studio are you building with (if any)?
2013

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
2013

Visual Studio Extension version in major.minor.release.build format)
 0.9.21.62588

* Which version of .NET are you building with?
4.6.1

* Describe the problem and the steps to reproduce it.
When installing the VS2013 extension i got a NullReferenceException:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.TryGetProductVersion(String productVersionString, Version& productVersion)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.TryGetProductVersionFromPath(String path, Version& productVersion)
   at VSIXInstaller.SupportedVSSKU.get_VersionWithBuildRevisionInfo()
   at VSIXInstaller.App.IsValidSKUForExtension(SupportedVSSKU supportedSKU, IExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.ShouldAddSkuToValidSkuList(SupportedVSSKU sku, IInstallableExtension extension, List`1 validSKUs)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
