### ISSUE TITLE
VSIXInstaller doesn't find VS2017 if SQL Express 2017 is installed

### ISSUE THREAD

**Issue by Laskarzhevsky** [wixtoolset/issues#5817]
Microsoft VSIX Installer
Version         : 0.9.21.62588

Visual Studio Enterprise 2017
Version 15.7.1

Microsoft .Net Framework
Version 4.7.02556

Microsoft SLQ Server Management Studio
Version 17.7

Operating System
Windows 10 Pro 64-bit

Having VS2017 installed, do the following:
1. Download and install SQL Server Express 2017 from https://www.microsoft.com/en-ca/sql-server/sql-server-editions-express
2. Download and install SQL Server Management Studio 17.7 from https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017
3. Download and install Wix Toolset Visual Studio 2017 Extension from https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2017Extension

The following is the complete log from VSIX Installer:
2018-05-19 06:49:46 - Microsoft VSIX Installer
2018-05-19 06:49:46 - -------------------------------------------
2018-05-19 06:49:46 - Initializing Install...
2018-05-19 06:49:46 - Extension Details...
2018-05-19 06:49:46 - 	Identifier      : WixToolset.VisualStudioExtension.Dev15
2018-05-19 06:49:46 - 	Name            : Wix Toolset Visual Studio 2017 Extension
2018-05-19 06:49:46 - 	Author          : .NET Foundation and contributors
2018-05-19 06:49:46 - 	Version         : 0.9.21.62588
2018-05-19 06:49:46 - 	Description     : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
2018-05-19 06:49:46 - 	Locale          : en-US
2018-05-19 06:49:46 - 	MoreInfoURL     : http://wixtoolset.org/
2018-05-19 06:49:46 - 	InstalledByMSI  : False
2018-05-19 06:49:46 - 	SupportedFrameworkVersionRange : [4.0,)
2018-05-19 06:49:46 - 
2018-05-19 06:49:46 - 	Supported Products : 
2018-05-19 06:49:46 - 		Microsoft.VisualStudio.Community
2018-05-19 06:49:46 - 			Version : [15.0,16.0)
2018-05-19 06:49:46 - 
2018-05-19 06:49:46 - 	References      : 
2018-05-19 06:49:46 - 
2018-05-19 06:49:46 - Searching for applicable products...
2018-05-19 06:49:49 - Found installed product - Global Location
2018-05-19 06:49:49 - Found installed product - ssms
2018-05-19 06:49:49 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
