### ISSUE TITLE
Melt.exe crashes when melting an MSI and running with elevated privileges

### ISSUE THREAD

**Issue by dtuchlinsky** [wixtoolset/issues#5859]
* Which version of WiX are you building with?
> WiX v3.11.1
* Which version of Visual Studio are you building with (if any)?
> N/A
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> N/A
* Which version of .NET are you building with?
> .NET v4.6.1
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> (Windows version)
* Describe the problem and the steps to reproduce it.
> Melt.exe crashes when melting an MSI if it is run with elevated UAC privileges.  Melt will run fine in the same environment if melt.exe is run without elevated UAC privileges.  This was working fine until KB4338420 was installed on our build servers which caused all patch builds to fail.
> Steps to reproduce:
>- Install “Update for Microsoft .NET Framework 4.6.1 (KB4338420)” on a Windows 2008 R2 server (also reproducible on Windows 7).
>- Launch a command prompt with elevated UAC privileges (i.e. run as administrator)
>- Run melt against an MSI with the matching wixpdb

> Output from melt below
>"C:\Program Files (x86)\WiX Toolset v3.11.1\melt.exe" "test.msi" "test.wixpdb" -pdb "test.wixpdb"  
Windows Installer XML Toolset Melter version 3.11.1.2318
Copyright (c) .NET Foundation and contributors. All rights reserved.

>test.msi / test.wixpdb
melt.exe : error MELT0001 : Could not find a part of the path 'C:\Users\test\AppData\Local\Temp\p1nkl0pw\p1nkl0pw.cab'.

>Exception Type: System.IO.DirectoryNotFoundException

>Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.Tools.WindowsInstallerXml.Pdb.Load(Stream stream, Uri uri, Boolean suppressVersionCheck, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Pdb.Load(String path, Boolean suppressVersionCheck, Boolean suppressSchema)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Melt.MeltProduct()
   at Microsoft.Tools.WindowsInstallerXml.Tools.Melt.Run(String[] args)
* Describe the behavior you expected and how it differed from the actual behavior.
> Melt should be able to melt an MSI when running with or without elevated privileges.

**Comment by BMurri** [comment]
Does installing the update described at https://support.microsoft.com/en-us/help/4345913 resolve the issue? The MSI APIs provided in Windows make an extensive use of COM and tend to mask OS errors with it's own assumptions.

**Comment by dtuchlinsky** [comment]
In Microsoft.Tools.WindowsInstallerXml.Pdb.Load(Stream stream, Uri uri, bool suppressVersionCheck, bool suppressSchema), an instance of TempFileCollection is created to generate a name of 
`                using (TempFileCollection tempFileCollection = new TempFileCollection())
                {
                    cabPath = tempFileCollection.AddExtension("cab", true);
                }`

KB4338420 changed the behaviour of TempFileCollection.  Before KB4338420 was installed, TempFileCollection::AddExtension would return a file path in the %TMP% directory (i.e. C:\Temp\zwlyt205.cab).  After KB4338420 is installed, it would create random subdirectory in %TMP% and return a file path in this directory (i.e. C:\DaveTemp\zwlyt205\zwlyt205.cab).

The "using" statement in Pdb.Load would cause the instance of the TempFileCollection to be disposed of which will delete the temporary folder in the %TMP% directory since the cab file has not yet been created.  Later in the function another instance of TempFileCollection is created and the cab file is added to this.

A solution to this is to avoid using the "using" statement to prevent the premature garbage collection. 
 Microsoft.Tools.WindowsInstallerXml.Pdb.Load also uses the TempFileCollection, however, it avoids creating a temporary instance of it.

**Comment by barnson** [comment]
If the fix is simple/safe, we'd take it in v3.14. (We'll investigate the PR.) Otherwise, the bug doesn't occur in WiX v4.0 because it doesn't use `TempFileCollection` at all.

**Comment by jakebullet70** [comment]
What is the status of this bug? I am running into the same problem as mentioned here on our Server 2008 build machine. I did try and install 'https://support.microsoft.com/en-us/help/4345913' as mentioned above but this did not help. I see that a fix has been submitted but it looks like it has not been merged.

**Comment by CC4C37A9-A0F6-43C9-B966-B26952D6B656** [comment]
Hi guys,
I managed to solve that issue by Wix Toolset 3.11 by the turning the Windows UAC back on. 
It was OFF on my new windows box and ON my my old windows box where it's working like a charm.

Please note:
Turn the Windows UAC back on. With that enabled, no program you start will automatically run as administrator

Best regards,
Wanderson PIN

**Comment by vipallav** [comment]
Hi guys,

Any update on fixing of this issue?
Is there any workaround to fix the issue, I am facing with windows server 2008 R2 with 3.14.0.1703? or If can be solved by any updated version of wix?

Thanks,
Vipallav

**Comment by vipallav** [comment]
> Hi guys,
> 
> Any update on fixing of this issue?
> Is there any workaround to fix the issue, I am facing with windows server 2008 R2 with 3.14.0.1703? or If can be solved by any updated version of wix?
> 
> Thanks,
> Vipallav

I am sorry to ask the question again but this is currently very urgent issue as need to provide urgent patch for my product. Can somebody help me on this?

Thank you very much in advance!!

**Comment by jakebullet70** [comment]
Nope, never fixed and I do not see Microsoft fixing it as they want people to move on from Server 2008 even though I think it is officially supported till like 2020. The Wix guys seem to have the fix but it has not to my knowledge been fixed as the bug is still open.  We fixed ours by upgrading from 2008 to server 2012.

**Comment by robmen** [comment]
The issue is still open so it shouldn't be fixed (if it was fixed, this issue should be closed).

@vipallav, if you need urgent and guaranteed support on issues, consider a [commercial option][com] instead of depending on volunteers. We are focused on WiX v4 at this time.

[com]: https://www.firegiant.com/support-options/

**Comment by vipallav** [comment]
Thank you very much for the update. Just for info, When WiX v4 is planned to release?

**Comment by BMurri** [comment]
Basically, when it's done. Every contributor appears to be a volunteer, but it feels like it's close.

A few months, at least, is what I see.

**Comment by vipallav** [comment]
Okay. Thanks for the update.

**Comment by vipallav** [comment]
Hi Guys, looks now the same issue with Windows Server 2012 and 2016 also. It was working with me after upgrading to Windows Server 2016 but since few days getting the same error which I used to get with Windows Server 2008 R2. Is anyone also facing same?

**Comment by vipallav** [comment]
> Hi Guys, looks now the same issue with Windows Server 2012 and 2016 also. It was working with me after upgrading to Windows Server 2016 but since few days getting the same error which I used to get with Windows Server 2008 R2. Is anyone also facing same?

Hi @jakebullet70 you mentioned in your previous comment that it was fixed by upgrading to Windows Server 2012. Are you also facing the issue now with 2012?

**Comment by jakebullet70** [comment]
@vipallav I do not know as I was pulled into another project. At this point we do not use Wix for any patching at all.

**Comment by vipallav** [comment]
> @vipallav I do not know as I was pulled into another project. At this point we do not use Wix for any patching at all.

Thanks for the response @jakebullet70.

**Comment by jakebullet70** [comment]
@vipallav Did you find a fix for this? I just got pulled back into this and it is failing on Server 2016 wirth the same error.
