### ISSUE TITLE
 Light.exe Exception on Team Build Wix 3.8 Access to the path 'C:\Users\username\AppData\Local\Temp\ssvduzbf\bundle-attached.cab' is denied.

### ISSUE THREAD

**Issue by kramer9802** [wixtoolset/issues#5866]
UNHANDLED EXCEPTIONS FROM PROCESS 1832:
=====================
8/20/2018 7:37:54 AM
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\svc-TFSBLD-ARGO\AppData\Local\Temp\ssvduzbf\bundle-attached.cab' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
   at Microsoft.Tools.WindowsInstallerXml.Common.RecursiveFileAttributes(String path, FileAttributes fileAttribute, Boolean markAttribute)
   at Microsoft.Tools.WindowsInstallerXml.Common.DeleteTempFiles(String path, IMessageHandler messageHandler)
   at Microsoft.Tools.WindowsInstallerXml.WixBinder.DeleteTempFiles()
   at Microsoft.Tools.WindowsInstallerXml.Binder.DeleteTempFiles()
   at Microsoft.Tools.WindowsInstallerXml.Binder.Cleanup(Boolean tidy)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Main(String[] args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(Object parameters)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
===================

* Which version of WiX are you building with?

3.8.1128.0

* Which version of Visual Studio are you building with (if any)?

> Team Build Is running VS 2013

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

3.8.1128.0

* Which version of .NET are you building with?

>.net 4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

The build to produce the wix installer had been working fine for several years, but now only works about 1 out of 4 times. It gets this error nightly and then gets this error quiet often when queued manually.

* Describe the behavior you expected and how it differed from the actual behavior.

Build to Complete is expected, but fails because of above error.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
