### ISSUE TITLE
WiX v4 Crashes Visual Studio During Build (Merge Module)

### ISSUE THREAD

**Issue by iswix-llc** [wixtoolset/issues#5875]
* Which version of WiX are you building with?
4.0.0.5918

* Which version of Visual Studio are you building with (if any)?
VS 2017 Enterprise 15.8.2 (repro on VS2013 and VS2015 also)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
VS2017 09.21.62588

* Which version of .NET are you building with?
N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.

I used IsWiX to create a simple MSM/MSI combo containing a single EXE with a shortcut. (Source attached)  When building it in Visual Studio  the entire IDE is crashed and the following is found in EventViewer.

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WixToolset.Bind.Databases.ExtractMergeModuleFilesCommand.CreateFacadesForMergeModuleFiles(WixToolset.Data.Rows.WixMergeRow, System.Collections.Generic.List`1<WixToolset.Bind.Databases.FileFacade>, System.Collections.Generic.Dictionary`2<System.String,WixToolset.Bind.Databases.FileFacade>)
   at WixToolset.Bind.Databases.ExtractMergeModuleFilesCommand.Execute()
   at WixToolset.Bind.BindDatabaseCommand.Execute()
   at WixToolset.Binder.BindDatabase(WixToolset.Data.Output, System.String, System.Collections.Generic.IEnumerable`1<WixToolset.Bind.FileTransfer> ByRef, System.Collections.Generic.IEnumerable`1<System.String> ByRef)
   at WixToolset.Binder.Bind(WixToolset.Data.Output, System.String)
   at WixToolset.Tools.Light.Run()
   at WixToolset.Tools.Light.Execute(System.String[])
   at WixToolset.Tools.Light.Main(System.String[])

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at WixToolset.Build.Tasks.WixToolTask.ExecuteToolThread(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

[Installer.zip](https://github.com/wixtoolset/issues/files/2369293/Installer.zip)

**Comment by robmen** [comment]
This was fixed by https://github.com/wixtoolset/Core/commit/6b30680fd7a712b45538c3f0a89d652f0457a893
