### ISSUE TITLE
v4 - Can't compile loc string in number column

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#5948]
See failing test added in https://github.com/wixtoolset/Core/pull/24

> System.ArgumentException : Cannot convert string '!(loc.CustomFontSize)' to a 'number' field type.
Parameter name: value
Stack Trace:
  C:\src\mynewwix4\Data\src\WixToolset.Data\IntermediateFieldExtensions.cs(387,0): at WixToolset.Data.IntermediateFieldExtensions.Set(IntermediateField field, String value)
  C:\src\mynewwix4\Data\src\WixToolset.Data\IntermediateFieldExtensions.cs(442,0): at WixToolset.Data.IntermediateFieldExtensions.Set(IntermediateField field, IntermediateFieldDefinition definition, String value)
  C:\src\mynewwix4\Data\src\WixToolset.Data\IntermediateTupleExtensions.cs(99,0): at WixToolset.Data.IntermediateTupleExtensions.Set(IntermediateTuple tuple, Int32 index, String value)
  C:\src\mynewwix4\Core\src\WixToolset.Core\Compiler.cs(16312,0): at WixToolset.Core.Compiler.ParseTextStyleElement(XElement node)
  C:\src\mynewwix4\Core\src\WixToolset.Core\Compiler.cs(15575,0): at WixToolset.Core.Compiler.ParseUIElement(XElement node)
  C:\src\mynewwix4\Core\src\WixToolset.Core\Compiler.cs(6230,0): at WixToolset.Core.Compiler.ParseFragmentElement(XElement node)
  C:\src\mynewwix4\Core\src\WixToolset.Core\Compiler.cs(20510,0): at WixToolset.Core.Compiler.ParseWixElement(XElement node)
  C:\src\mynewwix4\Core\src\WixToolset.Core\Compiler.cs(143,0): at WixToolset.Core.Compiler.Compile(ICompileContext context)
  C:\src\mynewwix4\Core\src\WixToolset.Core\CommandLine\BuildCommand.cs(199,0): at WixToolset.Core.CommandLine.BuildCommand.CompilePhase(IDictionary`2 preprocessorVariables, IEnumerable`1 sourceFiles)
  C:\src\mynewwix4\Core\src\WixToolset.Core\CommandLine\BuildCommand.cs(92,0): at WixToolset.Core.CommandLine.BuildCommand.Execute()
  C:\src\mynewwix4\Core\src\WixToolset.Core.TestPackage\WixRunner.cs(42,0): at WixToolset.Core.TestPackage.WixRunner.Execute(String[] args, IServiceProvider serviceProvider, List`1& messages)
  C:\src\mynewwix4\Core\src\WixToolset.Core.TestPackage\WixRunner.cs(22,0): at WixToolset.Core.TestPackage.WixRunner.Execute(String[] args)
  C:\src\mynewwix4\Core\src\test\WixToolsetTest.CoreIntegration\MsiFixture.cs(219,0): at WixToolsetTest.CoreIntegration.MsiFixture.CanBuildDialogsInInstallUISequence()

**Comment by rseanhall** [comment]
(I prefer linking PRs instead of commits)

https://github.com/wixtoolset/Data/pull/65
https://github.com/wixtoolset/Core/pull/160
