### ISSUE TITLE
Light v3.11.1: error LGHT0001 : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

### ISSUE THREAD

**Issue by yingyyliu** [wixtoolset/issues#6077]
Please help!

I'm using WiX Toolset 3.11.1 NuGet package to compile my project. Unfortunately, it gives me the error:

```
Windows Installer XML Toolset Linker version 3.11.1.2318
Copyright (c) .NET Foundation and contributors. All rights reserved.

light.exe : error LGHT0001 : The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

Exception Type: System.IO.FileNotFoundException

Stack Trace:
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Tools.WindowsInstallerXml.Binder.ExtractCabinets(Hashtable cabinets)
   at Microsoft.Tools.WindowsInstallerXml.Binder.BindDatabase(Output output, String databaseFile)
   at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args) in C:\agent\_work\8\s\src\tools\light\light.cs:line 453
Binder temporary directory located at 'C:\Users\yliu\AppData\Local\Temp\hqgrztl2\hqgrztl2'.
Validator temporary directory located at 'C:\Users\yliu\AppData\Local\Temp\zodz1jd3\zodz1jd3'.
```

Would you please help me to debug light.exe. How can I get more information about what files are missing. My aim is to use the WiX 3.11.1  NuGet package to produce the installation package in msi format.

**Comment by robmen** [comment]
There is no official WiX v3 NuGet package. You are using a bootleg .nupkg that could be doing anything to your build system. It is not affiliated with us in any way shape or form.
