### ISSUE TITLE
WiX Toolset Visual Studio Extension v1.0.0.4 causes problems when building with NUKE

### ISSUE THREAD

**Issue by snowbirder** [wixtoolset/issues#6148]
## Bugs

* Which version of WiX are you building with?
> WiX Toolset v3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
> Visual Studio 2019 16.4.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> WiX Toolset Visual Studio Extension 1.0.0.4

* Which version of .NET are you building with?
> .NET Version 4.8

* Describe the problem and the steps to reproduce it.
In our Visual Studio 2019 solution we have > 100 C# projects and > 10 WiX projects. 
We've recently changed to use the NUKE build system. Unfortunately, we're experiencing
issues when the "WiX Toolset Visual Studio Extension" is enabled, and we start a NUKE build.

The symptoms are seen in NUKE as this:
```
The process cannot access the file '************\obj\Debug\net472\******.assets.cache' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at Nuke.Common.IO.FileSystemTasks.CopyRecursivelyInternal(String source, String target, DirectoryExistsPolicy directoryPolicy, FileExistsPolicy filePolicy, Func`2 excludeDirectory, Func`2 excludeFile)
   at Nuke.Common.IO.FileSystemTasks.<>c__DisplayClass21_0.<CopyRecursivelyInternal>b__1(String x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.IO.FileSystemTasks.<>c__DisplayClass21_0.<CopyRecursivelyInternal>b__1(String x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.IO.FileSystemTasks.<>c__DisplayClass21_0.<CopyRecursivelyInternal>b__1(String x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.IO.FileSystemTasks.CopyDirectoryRecursively(String source, String target, DirectoryExistsPolicy directoryPolicy, FileExistsPolicy filePolicy, Func`2 excludeDirectory, Func`2 excludeFile)
   at Build.<get_CopyContext>b__13_1() in *********************\build_nuke\Build.cs:line 135
   at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_0(Action x)
   at Nuke.Common.Utilities.Collections.EnumerableExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode)
```
and the build fails. As soon as we close Visual Studio 2019, the problem goes away.
It also goes away when disabling the "WiX Toolset Visual Studio Extension". 
When we do the NUKE build, we aren't doing anything in Visual Studio 2019, so we belive there must be some kind of background task in WiX that does this. It always seems related to *.assets.cache files being accessed.

* Describe the behavior you expected and how it differed from the actual behavior.
I expect that you can have Visual Studio 2019 solution open, while building in NUKE, without the "WiX Toolset Visual Studio Extension" causing issues.

**Comment by barnson** [comment]
Nothing like that in WiX. We're not aware of anything Votive does that would cause a problem like this. If you can pinpoint something WiX is doing wrong, we can take a look.

**Comment by snowbirder** [comment]
Thanks for looking into it. Will investigate further and try to make a reproducible case.

**Comment by BMurri** [comment]
When you do, please bring the case to the wix-users email list, where we discuss these things among the toolset developers and other consumers of the toolset to help each other determine whether there's an actionable bug or something that needs better documentation. From there we'll direct you back to this or a new issue as appropriate.
