### ISSUE TITLE
Harvesting .net 5 (core) DLL with .comhost. dll crashes heat

### ISSUE THREAD

**Issue by nbelyh** [wixtoolset/issues#6275]
* Which version of WiX are you building with?
> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
> 2019

* Which version of .NET are you building with?
> .NET 5

* Describe the problem and the steps to reproduce it.

Build a DLL using .net 5 and eanble com hosting for it. This produces two dlls - the main one and the .comhost.dll that is to be registered for com hosting. Now try to harvest informationg from the comhost dll using this command:
```
> heat file <libfile>.comhost.dll -o out.wxs
```

The heat crashes with the following message:

```
> heat file VisioComAddinNet5.comhost.dll -o out.wxs
Windows Installer XML Toolset Toolset Harvester version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

heat.exe : error HEAT0001 : '.', hexadecimal value 0x00, is an invalid character.

Exception Type: System.ArgumentException

Stack Trace:
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteAttributeString(String localName, String value)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Class.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.File.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Component.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.DirectoryRef.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Fragment.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Wix.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Heat.Run(String[] args)
````

* Describe the behavior you expected and how it differed from the actual behavior.

Heat runs properly and produces COM registration information extracted from the .comhost.dll

---- 
Reference: building a COM component on dotnet core
https://docs.microsoft.com/en-us/dotnet/core/native-interop/expose-components-to-com

**Comment by barnson** [comment]
What's the exception?

**Comment by nbelyh** [comment]
Sorry, missed that part. Here it is:
```
heat.exe : error HEAT0001 : '.', hexadecimal value 0x00, is an invalid character
Exception Type: System.ArgumentException
```

I had similar issues with .net dll with my project: https://github.com/nbelyh/VisioPanelAddinVSTO
The reason for me was that "normal" .net could not load .net core assembly for discovering assembly metadata.

**Comment by barnson** [comment]
Can you attach the x.comhost.dll?

**Comment by nbelyh** [comment]
Attached the output folder: [here](https://unmanagedvisio.com/upload/VisioComAddinNet5.zip)

**Comment by nbelyh** [comment]
If I try to harvest the whole folder:
```
Windows Installer XML Toolset Toolset Harvester version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

heat.exe : warning HEAT5151 : Could not harvest data from a file that was expected to be an assembly: C:\Projects\VisioComAddinNet5\bin\Debug\VisioComAddinNet5\VisioComAddinNet5.dll. If this file is not an assembly you can ignore this warning. Otherwise, this error detail may be helpful to diagnose the failure: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
heat.exe : warning HEAT5151 : Could not harvest data from a file that was expected to be an assembly: C:\Projects\VisioComAddinNet5\bin\Debug\VisioComAddinNet5\ref\VisioComAddinNet5.dll. If this file is not an assembly you can ignore this warning. Otherwise, this error detail may be helpful to diagnose the failure: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
heat.exe : error HEAT0001 : '.', hexadecimal value 0x00, is an invalid character.

Exception Type: System.ArgumentException

Stack Trace:
   at System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteAttributeString(String localName, String value)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Class.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.File.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Component.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.DirectoryRef.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Fragment.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Serialize.Wix.OutputXml(XmlWriter writer)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Heat.Run(String[] args)
```

**Comment by rseanhall** [comment]
Reproduces in v3 and v4. Heat gets a stack imbalance warning when doing its registry harvesting magic, so not sure if I can trust the following. The `Description` string of a `Class` element has an embedded null which is likely causing the problem (`"CoreCLR COMHost Server\0ô筼\bÏ彯窺\0\0Ï↊窹ⱐô엔窺砜\bÏÏ"`).

**Comment by nbelyh** [comment]
Looks like .NET5 simply writes garbage to this key?!?! Take a look here:

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/installer/corehost/cli/comhost/comhost.cpp#L263-L274

```cpp
    res = ::RegSetValueExW(
    regKey.get(),
    nullptr,
    0,
    REG_SZ,
    reinterpret_cast<const BYTE*>(entry.type.c_str()),
    static_cast<DWORD>(sizeof(entry.type.size() + 1) * sizeof(entry.type[0])));
```

Shouldn't it be (without 'sizeof', otherwise you always get 8)???

```cpp
    reinterpret_cast<const BYTE*>(entry.type.c_str()),
    static_cast<DWORD>((entry.type.size() + 1) * sizeof(entry.type[0])));
```

**Comment by barnson** [comment]
Fixed in .NET 5.
