### ISSUE TITLE
dark.exe fails with exception when decompiling bundle that has its attached container removed (like when present in the package cache).

### ISSUE THREAD

**Issue by Ark-kun** [wixtoolset/issues#6315]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2.4516

* Describe the problem and the steps to reproduce it.

I wanted to unpack Microsoft App-V client setup: `appv_client_setup.exe` using `dark.exe`. I got an exception which does not seem actionable. I wanted to elarn more, so I've used verbose flag, but that did not add any inforrmation. The UX files got extracted, but nothing more.

```
>"C:\Program Files (x86)\WiX Toolset v3.11\bin\dark.exe" "A:\C_ProgramData_Package Cache\{510fdf8b-a76a-481e-8305-5ac92eb45ebd}\appv_client_setup.exe" -v -x exe.unpacked
Windows Installer XML Toolset Decompiler version 3.11.2.4516
Copyright (c) .NET Foundation and contributors. All rights reserved.

appv_client_setup.exe
dark.exe : error DARK0001 : Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception Type: System.Runtime.InteropServices.COMException

Stack Trace:
   at Microsoft.Tools.WindowsInstallerXml.Cab.Interop.NativeMethods.ExtractCab(String cabinet, String extractDirectory)
   at Microsoft.Tools.WindowsInstallerXml.Cab.WixExtractCab.Extract(String cabinetFile, String extractDir)
   at Microsoft.Tools.WindowsInstallerXml.BurnReader.ExtractAttachedContainer(String outputDirectory, String tempDirectory)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Dark.Run(String[] args)
```

* Describe the behavior you expected and how it differed from the actual behavior.

I expect dark.exe to succeed. Or at least print an actionable error message. Especially in verbose mode.

**Comment by barnson** [comment]
The .exe in the package cache doesn't contain any packages; they've already been extracted separately to the package cache.
