### ISSUE TITLE
CanPatchSwidTag Burn integration test failing

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6675]
Despite https://github.com/wixtoolset/issues/issues/6380 being fixed, the `CanPatchSwidTag` test is still failing.

```
Error Message:
   Assert.Equal() Failure
Expected: 1.0.0.0
Actual:   (null)
  Stack Trace:
     at WixToolsetTest.BurnE2E.PatchTests.VerifySwidTagVersion(String tagName, String expectedVersion) in C:\src\wix4\src\test\burn\WixToolsetTest.BurnE2E\PatchTests.cs:line 135
   at WixToolsetTest.BurnE2E.PatchTests.CanPatchSwidTag() in C:\src\wix4\src\test\burn\WixToolsetTest.BurnE2E\PatchTests.cs:line 73
```

**Comment by robmen** [comment]
Despite the word `Patch` being in the name of the test, this test doesn't seem to be a patching issue. The test code appears to have been ported over broken as it refers to the deprecated SWID tag spec (2009), not the new SWID tag spec (2015). The test code needs to be updated to read the correct SWID tag elements and read from the correct install location.
