### ISSUE TITLE
Random failures installing Votive

### ISSUE THREAD

**Issue by JVimes** [wixtoolset/issues#6797]
## Bugs

* Which version of WiX are you building with?

> v3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Community 2022 (64-bit) version 17.2.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.18

### Describe the problem and the steps to reproduce it.

When trying to install Votive:

- Sometimes the install reports success but the extension doesn't appear in Visual Studio ([false_success.log](https://github.com/wixtoolset/issues/files/8839240/false_success.log))
- Sometimes the install works ([true_success.log](https://github.com/wixtoolset/issues/files/8839244/true_success.log))
- Sometimes the install fails ([failure.log](https://github.com/wixtoolset/issues/files/8839241/failure.log))

Those logs are identical except:

- Temp folder names and process IDs differ.
- false_success has an all-caps path vs true_success  
    _false_success.log_  
    ```
    The extension has been installed to C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\EXTENSIONS\JJ23TW0H.TX1\
    ```
    _true_success.log_  
    ```
    The extension has been installed to C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\jj23tw0h.tx1
    ```
- failure.log has an error referencing a drive letter I don't have (D:).  
    Well, I did have a D: drive but it was my SD card and I removed it (no change).
```
Install Error : Microsoft.VisualStudio.ExtensionManager.NestedExtensionInstallException: The extension 'WixToolset.VisualStudioExtension.Schemas3' nested within 'WixToolset.VisualStudioExtension.Dev17' failed to install.
Exception of type 'Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException' was thrown. ---> Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: Exception of type 'Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException' was thrown.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.RefreshExtractedPackageStream(String nestedVsixPath, IExtensionReference reference) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\InstallableExtensionImpl.cs:line 683
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 849
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallNestedExtensions(InstallableExtensionImpl parentExtension, IInstalledExtension installedParentExtension, ZipPackage parentVSIX, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 874
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 1055
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 265
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 399
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp) in D:\a\_work\1\s\src\product\extensionManager\Microsoft.VisualStudio.ExtensionEngine\Impl\EngineModules\InstallModule.cs:line 894
```

Notes:

- I tried repairing Visual Studio, running ChkDsk.exe/DISM.exe/sfc.exe, and rebooting.
- This happens on my personal desktop and laptop (nothing from IT installed) with up-to-date Windows 10.
- My only antivirus is Windows Defender. It didn't show any notifications.
- I tried exiting all other apps. I don't have any that I think could have interfered.

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, I'd recommend following up on this issue that seems to track new failures in 17.2: https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

**Comment by JVimes** [comment]
Thank you. I'll watch that.

**Comment by barnson** [comment]
Tracking this class of bug at https://github.com/wixtoolset/issues/issues/6803.
