### ISSUE TITLE
Wix Toolset Visual Studio 2019 Extension doesn't install and throws error

### ISSUE THREAD

**Issue by Prakaash786** [wixtoolset/issues#6834]
Hi Team,

I have a Visual Studio 2019 Enterprise Edition, I have installed the Wix Build Tools v3.11.4516.0. I am trying to install the Wix Toolset Visual Studio 2019 Extension using extension manager and manually using votive2019.vsix file but it doesn't install and throws error.

Below is the error image and the log file attached.
![VotiveError](https://user-images.githubusercontent.com/42036013/179288193-4eaf2f44-b67f-4c16-892d-952b42c1f54b.JPG)
[dd_VSIXInstaller_20220713095717_07b4.log](https://github.com/wixtoolset/issues/files/9123162/dd_VSIXInstaller_20220713095717_07b4.log)

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

**> v3.11.4516.0**

* Which version of Visual Studio are you building with (if any)?

Microsoft Visual Studio Enterprise 2019
Version 16.11.16
VisualStudio.16.Release/16.11.16+32602.291
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA805
Microsoft Visual C++ 2019

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

**> Wix Toolset Visual Studio 2019 Extension v3.11**

* Which version of .NET are you building with?

> Microsoft .NET Framework
Version 4.8.04084
Version 3.51 (pre-requisite for wix is also installed)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

**> Windows 10 Enterprise,  Version 21H2**

* Describe the problem and the steps to reproduce it.

I have a Visual Studio 2019 Enterprise Edition, I have installed the Wix Build Tools v3.11.4516.0. I am trying to install the Wix Toolset Visual Studio 2019 Extension using extension manager and manually using votive2019.vsix file but it doesn't install and throws error. The file error is shown in a .jpg file and a log file, both are attached for your reference.

* Describe the behavior you expected and how it differed from the actual behavior.

After installation of the VS2019 enterprise edition and Wix build tools installed, it should install it but it is not installing. Restarted my system but nothing worked.

Do you think that Wix Extension only works for professional edition and not the community / enterprise ediiton? 

Kindly have a look and advise.

**Comment by barnson** [comment]
This doesn't appear to be related to WiX:

    7/13/2022 9:57:18 AM - Found installed product - Visual Studio Enterprise 2019
    7/13/2022 9:57:18 AM - System.InvalidOperationException: VSHiveStub.exe failed: Unknown error
       at VSIXInstaller.LocationBasedSKU.SettingsManagerData.get_RegRootHiveOverride()
       at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
       at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
       at VSIXInstaller.SupportedVSSKU.get_Host()
       at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
       at System.Lazy`1.CreateValue()
       at System.Lazy`1.LazyInitValue()
       at System.Lazy`1.get_Value()
       at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
       at VSIXInstaller.ExtensionService.TryAddSkuToValidSkuList(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)

You might try repairing Visual Studio to try to fix that problem.

**Comment by Prakaash786** [comment]
Hi Bob,

Thank you for your reply, Do you know if WIX is incompatible with Microsoft Enterprise edition? 

Regards,
Chandra

**Comment by barnson** [comment]
The WiX VS extension supports VS Enterprise.

**Comment by Prakaash786** [comment]
Hi, I have uninstalled Visual Studio Enterprise edition and reinstalled the Visual Studio Professional edition but I am getting the same error. I followed some links and it suggested to repair the visual studio or try to install the extension in admin mode. I tried both the solutions but no luck. 

getting the error log
[dd_VSIXInstaller_20220726222632_50e8.log]

(https://github.com/wixtoolset/issues/files/9191857/dd_VSIXInstaller_20220726222632_50e8.log)

Does anyone know about the issue and help.

**Comment by robmen** [comment]
This still seems to be the problem. As Bob mentioned above, you'll want to follow up with the Visual Studio team. They own the installer technology that seems to be failing with this error:

```
7/26/2022 10:26:33 PM - System.InvalidOperationException: VSHiveStub.exe failed: Unknown error
   at VSIXInstaller.LocationBasedSKU.SettingsManagerData.get_RegRootHiveOverride()
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.TryAddSkuToValidSkuList(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
7/26/2022 10:26:33 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Prakaash786** [comment]
Thank you Rob, I will contact microsoft. Will update once I get the solution.
