### ISSUE TITLE
Encountered a problem, light.exe : error LGHT0001 : '.', hexadecimal value 0x00, is an invalid character.  but don't know which 4.0 version contains the fix code.

### ISSUE THREAD

**Issue by beiluonever** [wixtoolset/issues#6916]
I download 4.0.0.5918 from https://wixtoolset.org/releases/v4-0-0-5918/. but found this error when I build msi package.

```
light.exe : error LGHT0001 : '.', hexadecimal value 0x00, is an invalid character.

Exception Type: System.ArgumentException

Stack Trace:
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at WixToolset.Data.Field.Write(XmlWriter writer)
   at WixToolset.Data.Row.Write(XmlWriter writer)
   at WixToolset.Data.Table.Write(XmlWriter writer)
   at WixToolset.Data.Output.Write(XmlWriter writer)
   at WixToolset.Data.Pdb.Write(XmlWriter writer)
   at WixToolset.Data.Pdb.Save(String path)
   at WixToolset.Bind.BindDatabaseCommand.Execute()
   at WixToolset.Binder.BindDatabase(Output output, String databaseFile, IEnumerable`1& fileTransfers, IEnumerable`1& contentPaths)
   at WixToolset.Binder.Bind(Output output, String file)
   at WixToolset.Tools.Light.Run()
   at WixToolset.Tools.Light.Execute(String[] args)

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '"C:\\Program Files (x86)\\WiX Toolset v4.0\\bin\\light.exe" -o output\\package\\xxx.msi output\\*.wixobj -cultures:en-us -loc en-us.wxl -ext
WixUIExtension.dll -ext WiXUtilExtension'
} WiX Toolset Linker version 4.0.0.5918
```
`
Its seems same like https://github.com/wixtoolset/issues/issues/4485 , but I do not know which Wix version fixed this issue.  I not a .Net develop, so that ,I do not want to build a version from source code. So Could any one help to  provide a build version or download link to help fix this ?

**Comment by barnson** [comment]
That's a very old build of WiX. See https://robmensching.com/blog/posts/2021/5/17/wix-toolset-v4-preview.0/.
