### ISSUE TITLE
error while signing bundle setup packages with insignia

### ISSUE THREAD

**Issue by horsonjin** [wixtoolset/issues#6967]
## Bugs
* Which version of WiX are you building with?
Wix version: 3.11.2

### Reproduce steps (Execute the following steps for multiple bundle setup packages)
insignia -ib bundle.exe -o engine.exe
... sign engine.exe
insignia -ab engine.exe bundle.exe -o bundle.exe  REM: here will throw the following exception
... sign bundle.exe

### Detailed Information
Exception Type: System.IO.IOException

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Tools.WindowsInstallerXml.BurnWriter.Open(String fileExe, IMessageHandler messageHandler)
   at Microsoft.Tools.WindowsInstallerXml.Inscriber.InscribeBundle(String bundleFile, String signedEngineFile, String outputFile)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Insignia.Run(String[] args)

### Possible Cause Reason
src/tools/wix/Inscriber.cs
Line 171
**File.Move(tempFile, outputFile);**

**Comment by robmen** [comment]
Fixed as part of https://github.com/wixtoolset/wix4/pull/258
