### ISSUE TITLE
ArgumentNullException when decompiled msi

### ISSUE THREAD

**Issue by itn3000** [wixtoolset/issues#7117]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0-rc1

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022(17.4.3)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> heatwave for vs2022 0.9.2

* Which version of .NET are you building with?

> dotnet-sdk 7.0.101

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 x64

* Describe the problem and the steps to reproduce it.

1. install wix-4.0.0-rc1 as dotnet global tool
2. create wix MSI project from VS2022(as "Package1")
3. build project
4. trying decompiling by `wix msi decompile path\to\Package1.msi`
> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

I expected to be output decompiling result as wxs, but ArgumentNullException was thrown as follows;

```
wix.exe : error WIX0001: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Xml.Linq.XAttribute..ctor(XName name, Object value)
   at WixToolset.Core.WindowsInstaller.Decompile.Decompiler.DecompileControlTable(Table table) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\Decompile\Decompiler.cs:line 3424
   at WixToolset.Core.WindowsInstaller.Decompile.Decompiler.DecompileTables(WindowsInstallerData output) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\Decompile\Decompiler.cs:line 2634
   at WixToolset.Core.WindowsInstaller.Decompile.Decompiler.Decompile(WindowsInstallerData output) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\Decompile\Decompiler.cs:line 184
   at WixToolset.Core.WindowsInstaller.WindowsInstallerDecompiler.DecompileDatabase(IWindowsInstallerDecompileContext context, IWindowsInstallerBackendHelper backendHelper, IFileSystem fileSystem, IPathResolver pathResolver) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\WindowsInstallerDecompiler.cs:line 102
   at WixToolset.Core.WindowsInstaller.WindowsInstallerDecompiler.Execute(IWindowsInstallerDecompileContext context) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\WindowsInstallerDecompiler.cs:line 86
   at WixToolset.Core.WindowsInstaller.WindowsInstallerDecompiler.Decompile(IWindowsInstallerDecompileContext context) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\WindowsInstallerDecompiler.cs:line 44
   at WixToolset.Core.WindowsInstaller.CommandLine.DecompilerSubcommand.ExecuteAsync(CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\CommandLine\DecompilerSubcommand.cs:line 108
   at WixToolset.Core.WindowsInstaller.CommandLine.WindowsInstallerCommand.ExecuteAsync(CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\WixToolset.Core.WindowsInstaller\CommandLine\WindowsInstallerCommand.cs:line 52
   at WixToolset.Tools.Program.Run(IServiceProvider serviceProvider, IMessageListener listener, String[] args, CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\wix\Program.cs:line 89
   at WixToolset.Tools.Program.Main(String[] args) in D:\a\wix4\wix4\src\wix\wix\Program.cs:line 43
```
> (Be as specific as you can and err on the side of providing too much information.)

`WixToolset.Core.WindowsInstaller\Decompile\Decompiler.cs:line 3424` is following url.
https://github.com/wixtoolset/wix4/blob/6580fe7b1ec4d33642f2ab828c7e7e1c7dbf8ee2/src/wix/WixToolset.Core.WindowsInstaller/Decompile/Decompiler.cs#L3424

**Comment by itn3000** [comment]
[Control.Text may be null](https://learn.microsoft.com/en-us/windows/win32/msi/control-table), so controlRow.Text should be checked whether it is null.
