### ISSUE TITLE
ProjectReferences and PackageReferences can encounter issues with TFMs

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#7132]
**Encountered at:** wixtoolset/wix4@6580fe7

**Detail:**

WiX declares a TFM of `native` to present as neutral a TFM as possible when `ProjectReference` and `PackageReference` are resolved. The `AssetTargetFallback` is used to create a "compatible list" of TFMs that must be kept up to date as new TFMs are introduced. Unfortunately, even this does not seem sufficient in all cases to support resolution of project and package references.

**Comment by DivineRage** [comment]
As discussed during the wix meeting yesterday, I went ahead and did some poking around to find a repro case. With success!

Repro steps;
1. Create a new project using the "MSI Package (WiX v4)"
2. Add a new "Console App" project (.NET 6.0) to the solution
3. Add the new project as a dependency to the Wix project.
4. Add the following snippet to the csproj of the Console App project. I unloaded the project, edited it in VS, and reloaded it.

```
  <ItemGroup>
    <PackageReference Include="Svg">
      <Version>3.0.84</Version>
    </PackageReference>
  </ItemGroup>
```

At this point it automatically tried restoring NuGet packages, and it gave me this issue; 

```
Error	MSB4018	The "ResolvePackageDependencies" task failed unexpectedly.
System.ArgumentException: Invalid framework version '0.0/win'.
   at NuGet.Frameworks.NuGetFramework.ParseFrameworkNameParts(IFrameworkNameProvider mappings, String[] parts, String& framework, Version& version, String& profile)
   at NuGet.Frameworks.NuGetFramework.ParseFrameworkName(String frameworkName, IFrameworkNameProvider mappings)
   at NuGet.Frameworks.NuGetFramework.Parse(String folderName, IFrameworkNameProvider mappings)
   at FireGiant.HeatWave.Build.Tasks.ResolvePackageDependencies.<GetPackageAndFileDefinitions>b__48_5(String tg)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at FireGiant.HeatWave.Build.Tasks.ResolvePackageDependencies.<GetPackageAndFileDefinitions>g__GetPackageDiagnosticLevel|48_0(LockFileLibrary package)
   at FireGiant.HeatWave.Build.Tasks.ResolvePackageDependencies.GetPackageAndFileDefinitions()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	WixPackageReferenceIssue4	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\FireGiant\HeatWave\FireGiant.HeatWave.PackageDependencyResolution.targets	185	
```

Wix `4.0.0-rc.1`
VS2022 `17.4.2`
FireGiant HeatWave `0.9.2.1`

**Comment by tstaec** [comment]
Would really like a workaround for this since completely prevents use. Adding "net5.0-windows7.0"to AssetTargetFallback worked for .net5 but not for net6 now.
Lowest package that triggered this for me was system.runtime.
