### ISSUE TITLE
WIX0001	System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

### ISSUE THREAD

**Issue by manikandankkr** [wixtoolset/issues#7173]
## Bugs

* Which version of WiX are you building with?

> (Wix 4.0 Preview)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio 2022)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (https://www.firegiant.com/wix/heatwave/)

* Which version of .NET are you building with?

> (.NET 6.0)

* Describe the problem and the steps to reproduce it.

Have used FireGaint HeatWave Extension to migrate the Wix 3 installer project to Wix 4 installer.
Have converted the each and every wxs files to Wix 4 installer files.
Have tried to build the project but the mentioned issue happened in wix.exe file.

![tempsnip](https://user-images.githubusercontent.com/32087032/213496458-2335e6bc-147c-4d76-9f91-d379d79e40fc.png)

**Comment by barnson** [comment]
Please provide a repo with WiX authoring that reproduces the problem or a binlog using MSBuild from the command line so we can get the full stack trace.

**Comment by siujay** [comment]
wix.exe : error WIX0001: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at WixToolset.Core.Compiler.AddProperty(SourceLineNumber sourceLineNumbers, Identifier propertyId, String value, Boolean admin, Boolean secure, Boolean hidden, Boolean fragment) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler.cs:line 363
   at WixToolset.Core.Compiler.ParsePropertyElement(XElement node) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler_Package.cs:line 1498
   at WixToolset.Core.Compiler.ParsePackageElement(XElement node) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler_Package.cs:line 302
   at WixToolset.Core.Compiler.ParseWixElement(XElement node) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler.cs:line 221
   at WixToolset.Core.Compiler.Compile(ICompileContext context) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler.cs:line 129
   at WixToolset.Core.CommandLine.BuildCommand.CompilePhase(IDictionary`2 preprocessorVariables, IEnumerable`1 sourceFiles, IReadOnlyCollection`1 includeSearchPaths, CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 188
   at WixToolset.Core.CommandLine.BuildCommand.ExecuteAsync(CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 106
   at WixToolset.Tools.Program.Run(IServiceProvider serviceProvider, IMessageListener listener, String[] args, CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\wix\Program.cs:line 89
   at WixToolset.Tools.Program.Main(String[] args) in D:\a\wix4\wix4\src\wix\wix\Program.cs:line 43
