### ISSUE TITLE
ArgumentOutOfRangeException in parsing Property value with wix4.0.0-rc2

### ISSUE THREAD

**Issue by itn3000** [wixtoolset/issues#7181]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> wix-4.0.0-rc.2

* Which version of Visual Studio are you building with (if any)?

> VisualStudio 2022(17.4.3)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> do not use Visual Studio Extension

* Which version of .NET are you building with?

> .NET SDK 7.0.101

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 x64

* Describe the problem and the steps to reproduce it.

1. create wixproj
2. create wxs as follows
3. compile with `dotnet build`

```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
    <Package Name="proptest" Manufacturer="TODO Manufacturer" Version="1.0.0.0"
        UpgradeCode="33ed89f3-755f-46a6-981f-692f90ede6ce">
        <Feature Id="Main">
            <ComponentGroupRef Id="All" />
        </Feature>
        <StandardDirectory Id="ProgramFilesFolder">
            <Directory Id="INSTALLFOLDER"></Directory>
        </StandardDirectory>
        <ComponentGroup Id="All">
            <Component Id="Component1" Directory="INSTALLFOLDER" Guid="ec745192-84c9-4ed4-8353-fc31d9c527a9">
                <CreateFolder />
            </Component>
        </ComponentGroup>
        <!-- if value is a[1] or [1], success compilation -->
        <Property Id="Abc" Value="ab[1]"/>
    </Package>
</Wix>
```

* Describe the behavior you expected and how it differed from the actual behavior.

Expected: success compilation
Actual: output following error and fail compilation(`-v:d` option is added in command line)

```
1:7>wix.exe : error WIX0001: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length') [D:\src\gitrepos\wix-sandbox\pr
       optest\proptest.wixproj]
            at System.String.Substring(Int32 startIndex, Int32 length)
            at WixToolset.Core.Compiler.AddProperty(SourceLineNumber sourceLineNumbers, Identifier propertyId, String value, Boolean admin, Boolean secure, Boolean hidden, Boolean f 
         ragment) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler.cs:line 363
            at WixToolset.Core.Compiler.ParsePropertyElement(XElement node) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler_Package.cs:line 1508
            at WixToolset.Core.Compiler.ParsePackageElement(XElement node) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler_Package.cs:line 312
            at WixToolset.Core.Compiler.ParseWixElement(XElement node) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler.cs:line 221
            at WixToolset.Core.Compiler.Compile(ICompileContext context) in D:\a\wix4\wix4\src\wix\WixToolset.Core\Compiler.cs:line 129
            at WixToolset.Core.CommandLine.BuildCommand.CompilePhase(IDictionary`2 preprocessorVariables, IEnumerable`1 sourceFiles, IReadOnlyCollection`1 includeSearchPaths, Cancel 
         lationToken cancellationToken) in D:\a\wix4\wix4\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 188
            at WixToolset.Core.CommandLine.BuildCommand.ExecuteAsync(CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line  
         106
            at WixToolset.Tools.Program.Run(IServiceProvider serviceProvider, IMessageListener listener, String[] args, CancellationToken cancellationToken) in D:\a\wix4\wix4\src\wi 
         x\wix\Program.cs:line 89
            at WixToolset.Tools.Program.Main(String[] args) in D:\a\wix4\wix4\src\wix\wix\Program.cs:line 43
         コマンドはコード -2146233086 で終了しました。
```

**Comment by ronfluegge** [comment]
Which version of WiX are you building with?
wix-4.0.0-rc.2

Which version of Visual Studio are you building with (if any)?
Visual Studio 2022(17.4.4)

Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
Heatwave for VS 2022 V. 0.9.4

Which version of .NET are you building with?
4.8

If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
the BUILD fails with the error below.

Describe the problem and the steps to reproduce it.

8>------ Rebuild All started: Project: ServerDropDown, Configuration: Release Any CPU ------
8>  ServerDropDown -> D:\Server Names2005\DropdownList\bin\Release\SetupConsole.exe
9>------ Rebuild All started: Project: DEServerSetupInstall_wix, Configuration: Release x86 ------
9>wix.exe : error WIX0001: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
9>Done building project "DEServerSetupInstall_wix.wixproj" -- FAILED.
========== Rebuild All: 8 succeeded, 1 failed, 0 skipped ==========

Compiled solution as release
wix.exe : error WIX0001: System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
