### ISSUE TITLE
SetProperty leads to an exception

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7225]
* Which version of WiX are you building with?

> wix4@HEAD

* Which version of Visual Studio are you building with (if any)?

> n/a

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> sdk\7.0.103\

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a

* Describe the problem and the steps to reproduce it.

> The following authoring results in an exception (that results in another exception, being fixed in https://github.com/wixtoolset/wix4/pull/358):

    <SetProperty Id="WixQuietExecCmdLine" Value="[%ComSpec] /c ECHO %NUMBER_OF_PROCESSORS%" Before="ConvolutedCoreCountCustomAction" />
    <CustomAction Id="ConvolutedCoreCountCustomAction" BinaryRef="Wix4UtilCA_X86" DllEntry="Wix4QuietExec_X86" Execute="immediate" Return="check" />

The exception is:

    WixToolset.Data.WixException
      HResult=0x80131500
      Message=Found action InstallUISequence/SetWixQuietExecCmdLine with a non-existent Before action 'ConvolutedCoreCountCustomAction'. The linker should have prevented this.
      Source=WixToolset.Core.WindowsInstaller
      StackTrace:
       at WixToolset.Core.WindowsInstaller.Bind.SequenceActionsCommand.SequenceActionSymbol(WixActionSymbol actionSymbol, Dictionary`2 requiredActionSymbols, Dictionary`2 firstReference) in z:\src\wix4\src\wix\WixToolset.Core.WindowsInstaller\Bind\SequenceActionsCommand.cs:line 594
       at WixToolset.Core.WindowsInstaller.Bind.SequenceActionsCommand.Execute() in z:\src\wix4\src\wix\WixToolset.Core.WindowsInstaller\Bind\SequenceActionsCommand.cs:line 148
       at WixToolset.Core.WindowsInstaller.Bind.BindDatabaseCommand.Execute() in z:\src\wix4\src\wix\WixToolset.Core.WindowsInstaller\Bind\BindDatabaseCommand.cs:line 171
       at WixToolset.Core.WindowsInstaller.MsiBackend.Bind(IBindContext context) in z:\src\wix4\src\wix\WixToolset.Core.WindowsInstaller\MsiBackend.cs:line 28
       at WixToolset.Core.Binder.BackendBind(IBindContext context) in z:\src\wix4\src\wix\WixToolset.Core\Binder.cs:line 67
       at WixToolset.Core.Binder.Bind(IBindContext context) in z:\src\wix4\src\wix\WixToolset.Core\Binder.cs:line 40
       at WixToolset.Core.CommandLine.BuildCommand.BindPhase(Intermediate output, IReadOnlyCollection`1 localizations, IReadOnlyCollection`1 filterCultures, String cabCachePath, Int32 cabbingThreadCount, IReadOnlyCollection`1 bindPaths, Dictionary`2 bindVariables, InputsAndOutputs inputsOutputs, CancellationToken cancellationToken) in z:\src\wix4\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 320
       at WixToolset.Core.CommandLine.BuildCommand.ExecuteAsync(CancellationToken cancellationToken) in z:\src\wix4\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 152
       at WixToolset.Tools.Program.Run(IServiceProvider serviceProvider, IMessageListener listener, String[] args, CancellationToken cancellationToken) in z:\src\wix4\src\wix\wix\Program.cs:line 98
       at WixToolset.Tools.Program.<Main>d__0.MoveNext() in z:\src\wix4\src\wix\wix\Program.cs:line 49

* Describe the behavior you expected and how it differed from the actual behavior.

> An error is unfortunate but tolerable. A crash is not.

**Comment by barnson** [comment]
`Sequence="execute"` fixes it.
