### ISSUE TITLE
Wix toolset incompatibility with Visual Studio 2022 17.6

### ISSUE THREAD

**Issue by jaytonic** [wixtoolset/issues#7505]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 1.0.0.22

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022 17.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.22

* Which version of .NET are you building with?

> .Net 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

>N/A

* Describe the problem and the steps to reproduce it.

> 
0. I was having Visual Studio 17.5.4 installed, with wix toolset installed. Everything works fine. 
1. I did update to Visual studio to the 17.6 version
2. Then I double click on any wxs
3. Visual Studio freeze and doesn't respond anymore.

- Also, I reverted back to the 17.5.4, and everything is working again.
- I also tried to remove and install again wix toolset, same issue occurs

* Describe the behavior you expected and how it differed from the actual behavior.

> Visual studio should open the wxs, the same as with the 17.5.4

**Comment by overcoil** [comment]
I am having a similar problem installing WiX v3 - Visual Studio 2022 Extension to a fresh install of Visual Studio 2022 Community Edition 17.6. I get the error:

This extension is not installable on any currently installed products.

My full install log with the error is as follow:

2023-05-26 1:50:36 PM - Microsoft VSIX Installer
2023-05-26 1:50:36 PM - -------------------------------------------
2023-05-26 1:50:36 PM - vsixinstaller.exe version:
2023-05-26 1:50:36 PM - 17.6.2164+g40888c9894
2023-05-26 1:50:36 PM - -------------------------------------------
2023-05-26 1:50:36 PM - Command line parameters:
2023-05-26 1:50:36 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\Votive2022 (1).vsix
2023-05-26 1:50:36 PM - -------------------------------------------
2023-05-26 1:50:36 PM - Microsoft VSIX Installer
2023-05-26 1:50:36 PM - -------------------------------------------
2023-05-26 1:50:37 PM - Initializing Install...
2023-05-26 1:50:37 PM - Searching for applicable products...
2023-05-26 1:50:38 PM - Found installed product - Visual Studio Community 2022
2023-05-26 1:50:38 PM - Found installed product - Global Location
2023-05-26 1:50:38 PM - Extension Details...
2023-05-26 1:50:38 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev17
2023-05-26 1:50:38 PM - 	Name               : WiX v3 - Visual Studio 2022 Extension
2023-05-26 1:50:38 PM - 	Author             : WiX Toolset
2023-05-26 1:50:38 PM - 	Version            : 1.0.0.22
2023-05-26 1:50:38 PM - 	Description        : Visual Studio integration for the WiX v3 Toolset - the most powerful set of tools available to create your Windows installation experience.
2023-05-26 1:50:38 PM - 	Locale             : en-US
2023-05-26 1:50:38 PM - 	MoreInfoURL        : https://wixtoolset.org/
2023-05-26 1:50:38 PM - 	InstalledByMSI     : False
2023-05-26 1:50:38 PM - 	SupportedFrameworkVersionRange : [4.5,)
2023-05-26 1:50:38 PM - 	SignatureState     : ValidSignature
2023-05-26 1:50:38 PM - 	SignedBy           : WiX Toolset (.NET Foundation)
2023-05-26 1:50:38 PM - 	Certificate Info   : 
2023-05-26 1:50:38 PM - 		-------------------------------------------------------
2023-05-26 1:50:38 PM - 		[Subject]       : CN=WiX Toolset (.NET Foundation), O=WiX Toolset (.NET Foundation), L=Redmond, S=Washington, C=US, SERIALNUMBER=603 389 068, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Washington, OID.1.3.6.1.4.1.311.60.2.1.3=US
2023-05-26 1:50:38 PM - 		[Issuer]        : CN=.NET Foundation Projects Code Signing CA2, O=.NET Foundation, C=US
2023-05-26 1:50:38 PM - 		[Serial Number] : 02FB939AB63B1F73AC9184F12FA400B0
2023-05-26 1:50:38 PM - 		[Not Before]    : 2022-04-05 5:00:00 PM
2023-05-26 1:50:38 PM - 		[Not After]     : 2025-04-05 4:59:59 PM
2023-05-26 1:50:38 PM - 		[Thumbprint]    : C832C5A08718E880B35FF10FA8F41C5B6FF6F561
2023-05-26 1:50:38 PM - 	Supported Products : 
2023-05-26 1:50:38 PM - 		Microsoft.VisualStudio.Community
2023-05-26 1:50:38 PM - 			Version : [17.0,18.0)
2023-05-26 1:50:38 PM - 			ProductArchitecture : amd64
2023-05-26 1:50:38 PM - 	References         : 
2023-05-26 1:50:38 PM - 		-------------------------------------------------------
2023-05-26 1:50:38 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas3
2023-05-26 1:50:38 PM - 		Name         : WiX Toolset v3 Schemas for Visual Studio
2023-05-26 1:50:38 PM - 		Version      : 
2023-05-26 1:50:38 PM - 		MoreInfoURL  : 
2023-05-26 1:50:38 PM - 		Nested       : Yes
2023-05-26 1:50:38 PM - 	Prerequisites      : 
2023-05-26 1:50:38 PM - 		-------------------------------------------------------
2023-05-26 1:50:38 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2023-05-26 1:50:38 PM - 		Name         : Visual Studio core editor
2023-05-26 1:50:38 PM - 		Version      : [17.0,18.0)
2023-05-26 1:50:38 PM - Signature Details...
2023-05-26 1:50:38 PM - 	Extension is signed with a valid signature.
2023-05-26 1:50:38 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by barnson** [comment]
I was able to install v1.0.0.22 on VS Professional v17.6.1 and v17.6.2 and create new projects and open files.

VSIX installation is controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
