### ISSUE TITLE
Exception thrown one time when Heatwave upgrades existing wix 4 setup, but then everything works

### ISSUE THREAD

**Issue by hfickes** [wixtoolset/issues#7524]
The following is with WiX 4.0.0
                                Visual Studio 2022 (17.6.2)
                                HeatWave for V2022  version 1.0.1
                                .Net Framework 4.8

We already upgraded from WiX 3 to 4 when using Visual Studio 2019 and all was working well.

We are now moving to VS 2022.  After installing Heatwave for VS 2022, Heatwave asked to convert the wixproj, even though it already is in WiX 4 format.

The following stack exception was shown and written to the HeatWaveConvert.log

[05/30/2023 13:55:30.777]: Converting project file Setup.wixproj...
[05/30/2023 13:55:32.281]: *** ERROR ***: Import failed with an exception.
System.InvalidOperationException: Duplicate attribute.
   at System.Xml.Linq.XElement.AddAttribute(XAttribute a)
   at System.Xml.Linq.XContainer.Add(Object content)
   at FireGiant.HeatWave.ProjectConversion.VotiveProjectConverter.<ConvertAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FireGiant.HeatWave.ProjectConversion.VotiveProjectConverter.<TryConvertAsync>d__11.MoveNext().
[05/30/2023 13:55:32.284]: ---- Project Setup: Converted 0 files.
[05/30/2023 13:55:32.284]: ---- Total time: 01.514
[05/30/2023 13:55:32.284]: ========== Import complete:  1 errors, 0 warnings

However, after this, the wixproj works fine and we have no other issues.  Also, no changes were made to any of the setup files such as the wxs and wixproj files.

Thank you

**Comment by FireGiantHelp** [comment]
We have ported this issue to https://github.com/firegiant/HeatWaveSupport/issues/40. This one can be closed. Thanks.
