### ISSUE TITLE
WIX0001: System.NotSupportedException: No data is available for encoding 1252

### ISSUE THREAD

**Issue by pfusik** [wixtoolset/issues#7612]
* Which version of WiX are you building with?

> 4.0.1+6e6eb478

* Which version of Visual Studio are you building with (if any)?

> 2022 Community 17.6.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> 7.0.306

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

```
C:\0\ci\git\win32\setup>cat cito.wxs
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">
        <Package Name="Ć Transpiler" Version="3.0.0" Manufacturer="Piotr Fusik" Language="1033" UpgradeCode="0c3e3a72-72a5-4426-a1ce-f3ebd49fc8e3">
                <Media Id="1" Cabinet="cito.cab" CompressionLevel="high" EmbedCab="yes" />
                <StandardDirectory Id="ProgramFiles6432Folder">
                        <Directory Id="INSTALLFOLDER" Name="cito">
                                <Component Id="cito.exe">
                                        <File Source="cito.exe" />
                                </Component>
                        </Directory>
                </StandardDirectory>
                <Feature Id="cito.exe">
                        <ComponentRef Id="cito.exe" />
                </Feature>
                <ui:WixUI Id="WixUI_InstallDir" InstallDirectory="INSTALLFOLDER" />
        </Package>
</Wix>

C:\0\ci\git\win32\setup>wix build -ext WixToolset.UI.wixext -b ../.. cito.wxs
wix.exe : error WIX0001: System.NotSupportedException: No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
   at System.Text.Encoding.GetDataItem()
   at System.Text.Encoding.get_WindowsCodePage()
   at WixToolset.Core.WindowsInstaller.Bind.CreateIdtFileCommand.TableToIdtDefinition(Table table, StreamWriter writer, Boolean keepAddedColumns) in D:\a\wix\wix\src\wix\WixToolset.Core.WindowsInstaller\Bind\CreateIdtFileCommand.cs:line 84
   at WixToolset.Core.WindowsInstaller.Bind.CreateIdtFileCommand.Execute() in D:\a\wix\wix\src\wix\WixToolset.Core.WindowsInstaller\Bind\CreateIdtFileCommand.cs:line 45
   at WixToolset.Core.WindowsInstaller.Bind.GenerateDatabaseCommand.ImportTables(Database db, String idtDirectory) in D:\a\wix\wix\src\wix\WixToolset.Core.WindowsInstaller\Bind\GenerateDatabaseCommand.cs:line 213
   at WixToolset.Core.WindowsInstaller.Bind.GenerateDatabaseCommand.Execute() in D:\a\wix\wix\src\wix\WixToolset.Core.WindowsInstaller\Bind\GenerateDatabaseCommand.cs:line 107
   at WixToolset.Core.WindowsInstaller.Bind.BindDatabaseCommand.Execute() in D:\a\wix\wix\src\wix\WixToolset.Core.WindowsInstaller\Bind\BindDatabaseCommand.cs:line 461
   at WixToolset.Core.WindowsInstaller.MsiBackend.Bind(IBindContext context) in D:\a\wix\wix\src\wix\WixToolset.Core.WindowsInstaller\MsiBackend.cs:line 28
   at WixToolset.Core.Binder.BackendBind(IBindContext context) in D:\a\wix\wix\src\wix\WixToolset.Core\Binder.cs:line 67
   at WixToolset.Core.Binder.Bind(IBindContext context) in D:\a\wix\wix\src\wix\WixToolset.Core\Binder.cs:line 40
   at WixToolset.Core.CommandLine.BuildCommand.BindPhase(Intermediate output, IReadOnlyCollection`1 localizations, IReadOnlyCollection`1 filterCultures, String cabCachePath, Int32 cabbingThreadCount, IReadOnlyCollection`1 bindPaths, Dictionary`2 bindVariables, InputsAndOutputs inputsOutputs, CancellationToken cancellationToken) in D:\a\wix\wix\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 319
   at WixToolset.Core.CommandLine.BuildCommand.ExecuteAsync(CancellationToken cancellationToken) in D:\a\wix\wix\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 152
   at WixToolset.Tools.Program.Run(IServiceProvider serviceProvider, IMessageListener listener, String[] args, CancellationToken cancellationToken) in D:\a\wix\wix\src\wix\wix\Program.cs:line 103
   at WixToolset.Tools.Program.Main(String[] args) in D:\a\wix\wix\src\wix\wix\Program.cs:line 48
```

* Describe the behavior you expected and how it differed from the actual behavior.

> Installer built or WiX gives a readable error message.

**Comment by BMurri** [comment]
The message `No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.` comes from DotNet, not WiX. It means that at least one character used doesn't exist in the 1252 code page and offers the less-then-helpful tip to start down the rabbit hole of finding an encoding that will work for the data provided.

**Comment by tcrass** [comment]
I also run into this error, but I doubt that it is a problem with my wxs file -- I'm pretty sure that it's free from any non-cp1252 characters. Strange, though, is, that the `No data is available for encoding 1252` error only occurs when the build is initiated by Jenkins (which runs as default system user). When issuing exactly the same dotnet build command directly from the command line, the build finishes successfully.
Another weird observation: When launched from Jenkins, the build creates an `obj\Release\_idts` folder, which contains two files called `_ForceCodepage.idt` and `Property.idt`, respectively. The former file's content looks like

```




1252	_ForceCodepage
```

This folder doesn't show up when calling the build directly.
Any ideas why two identical invocations might lead to these differences?

Cheers -- tcrass
