### ISSUE TITLE
ArgumentNullException in Visual Studio when linking custom WixExtension to Wix4 package

### ISSUE THREAD

**Issue by GennadyMaltsev** [wixtoolset/issues#7865]
**Installed products**
Wix: 4.0.2+644ed011
VS 2022 Enterprise x64: 17.7.4
HeatWave for VS2022: 1.0.2
WixToolset.Extensibility: 4.0.2
WiX Toolset VS Extension: 1.0.0.22
.NET 4.7.2, .NET Standard 2.0
Windows: 10 x64 RU, build 19044 

Hello, dear Wix4 team!
I have to inform you that linking to a WixExtension project from Wix4 package causes an error in Visual Studio. 
When we open or reload a Wix4 package project, VS displays an error that is shown in screenshot 1.
Referenced WixExtension only overrides the BasePreprocessorExtension class (screenshot 2).
If you comment or delete the task \<WixExtension\>...\</WixExtension\> then the error disappears
(see attached project Wix3to4Examples\Wix4Package\Wix4Package.wixproj, line 10-12).
I tried to change the target framework of Wix4Extension project to either netstandard2.0 or net472 but to no avail.

The log file VsProjectFault_449b9831-4c2b-4aee-a7c9-364331790129.failure.txt contains a text like this:

```
14.11.2023 11:26:15
LimitedFunctionality
System.AggregateException: Project system data flow 'DependenciesChangesDataSource: 25218967' closed because of an exception.
Value cannot be null.
Parameter name: evaluationProperties
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: evaluationProperties
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.IsImplicit(String projectFullPath, IImmutableDictionary`2 evaluationProperties)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.<Handle>g__CreateDependencyModel|10_1(String itemSpec, IProjectRuleSnapshot projectRuleSnapshot, Boolean isResolved, <>c__DisplayClass10_0& A_4)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.<Handle>g__HandleChanges|10_0(Boolean resolved, IProjectChangeDescription projectChange, <>c__DisplayClass10_0& A_3)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesRuleHandlerBase.Handle(String projectFullPath, IProjectChangeDescription evaluation, IProjectChangeDescription projectBuild, DependenciesChangesBuilder changesBuilder)
   at FireGiant.HeatWave.ProjectSystem.SolutionExplorer.Dependencies.DependenciesChangesDataSource.ProcessRuleChange(IProjectVersionedValue`1 data)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass9_0.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
<--- (Inner Exception #0) 
```

You can find both projects in the attached zip:
[Wix3to4Examples.zip](https://github.com/wixtoolset/issues/files/13375721/Wix3to4Examples.zip)

![Wix4 issue 1](https://github.com/wixtoolset/issues/assets/37130918/2ef4e938-5134-4998-8860-927551d9fc6a)
![Wix4 issue 2](https://github.com/wixtoolset/issues/assets/37130918/00ce15eb-bf71-4344-9630-a3aea42f27b9)

Best regards,
Gennady Maltsev

**Comment by FireGiantHelp** [comment]
This issue was migrated to location where community can report HeatWave issues: https://github.com/firegiant/HeatWaveSupport/issues/49

**Comment by nistrar** [comment]
for me it worked changing the sdk version
<Project Sdk="WixToolset.Sdk/4.0.4">

**Comment by mennowo** [comment]
I faced this issue; it seems to have been caused by mixing SDK versions for multiple WiX projects. Setting them all to 6.0.0 fixed the issue.
