### ISSUE TITLE
WixToolset.Dtf.CustomAction calling session.GetProductProperty throws an exception

### ISSUE THREAD

**Issue by AdvancedNotifier** [wixtoolset/issues#7983]
### WiX Version

4.0.3

### .NET or MSBuild or Visual Studio Version

17.8.6

### HeatWave Version

1.0.2.1

### Windows Version

Win 10.0.19.0.45

### Repro Steps

Execute inside a CustomAction:

    var myProperty = session.GetProductProperty("MyProperty")

... throws an exception:

    System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.EntryPointNotFoundException: Der Einstiegspunkt "MsiGetProductProperty" wurde nicht in der DLL "msi.dll" gefunden.
       bei WixToolset.Dtf.WindowsInstaller.NativeMethods.MsiGetProductProperty(Int32 hProduct, String szProperty, StringBuilder lpValueBuf, UInt32& cchValueBuf)
       bei WixToolset.Dtf.WindowsInstaller.Session.GetProductProperty(String property)

In English (my translation):

    System.Reflection.TargetInvocationException: A calling target has created an exception. ---> System.EntryPointNotFoundException: The entrypoint "MsiGetProductProperty" was not found in the DLL "msi.dll".
       at WixToolset.Dtf.WindowsInstaller.NativeMethods.MsiGetProductProperty(Int32 hProduct, String szProperty, StringBuilder lpValueBuf, UInt32& cchValueBuf)
       at WixToolset.Dtf.WindowsInstaller.Session.GetProductProperty(String property)

This exception is shown inside the log created with:

    MsiExec.exe /lv MyLog.log

### Actual Result

...

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by chrpai** [comment]
Have you tried this with an MSI built using WiX v3?  Also have you tried this on other machines?

**Comment by AdvancedNotifier** [comment]
No and no.

**Comment by chrpai** [comment]
This issue will get triaged on Tuesday by the WiX team.  Having that test data would point to an issue in v4 or just a corrupt machine being installed on.

**Comment by barnson** [comment]
`MsiGetProductProperty` takes a product handle and is not available to a custom action session. We'll leave this open for someone to figure out whether it should be removed.

**Comment by chrpai** [comment]
That was my memory/assumption but then I saw this:

https://learn.microsoft.com/en-us/windows/win32/msi/session-productproperty

I don't really feel like digging deep on this..  perhaps this is a bug in the session object / doco and when the DTF folks made the interop they just implemented it?
