### ISSUE TITLE
Unnamed bindpath not respected

### ISSUE THREAD

**Issue by Emdot** [wixtoolset/issues#8585]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

.NET 8.0.300

### HeatWave Version

1.0.4.5

### Windows Version

Win10 21H2

### Repro Steps

1. In a wxs file, use `Files` with `Include="**"`. Example:
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
	<Package Name="MyProduct" Version="1.0.0.0" Manufacturer="Example Corporation" UpgradeCode="{ABCDEFF7-BC0C-4393-ACD8-B2396B5C3564}"		>
                <Files Include="**" />
	</Package>
</Wix>
```
2. `wix build -bindPath ..\data test.wxs`
3. `wix msi decompile test.msi -o test.decompiled.wxs`
4. View the decompiled results

### Actual Result

The MSI included files from the source directory

### Expected Result

The MSI included files from the directory specified by the `-bindpath` argument.

The [documentation for `Files`](https://wixtoolset.org/docs/schema/wxs/files/) says of `**`: "If an unnamed bind path was specified, all files in that directory and its subdirectories."

Possibly related:
* If I use `!(bindpath)\**`, the build issues a warning `warning WIX8601: Missing directory for harvesting files: Could not find a part of the path 'C:\temp\wixtest\code\!(bindpath)'`
* When I use a named bind (`-bindPath main=C:\temp\wixtest\data`) I get a crash: `error WIX0001: System.UnauthorizedAccessException: Access to the path 'C:\Config.Msi' is denied.`

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by Emdot** [comment]
_Named_ bindpaths work for me in wixproj files. I don't know what's different about that vs. the command line.

**Comment by kobykahane** [comment]
This change appears to have broken harvesting when multiple unnamed bind paths are specified.

```
wix.exe error WIX0001: System.InvalidOperationException: Sequence contains more than one matching element

   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at WixToolset.Core.HarvestFilesCommand.ResolveBindPaths(SourceLineNumber sourceLineNumbers, String source) in D:\a\wix\wix\src\wix\WixToolset.Core\HarvestFilesCommand.cs:line 209
   at WixToolset.Core.HarvestFilesCommand.GetWildcardFiles(HarvestFilesSymbol harvestFile, IEnumerable`1 patterns) in D:\a\wix\wix\src\wix\WixToolset.Core\HarvestFilesCommand.cs:line 141
   at WixToolset.Core.HarvestFilesCommand.HarvestFiles(HarvestFilesSymbol harvestFile, IntermediateSection section, ISet`1 harvestedFiles) in D:\a\wix\wix\src\wix\WixToolset.Core\HarvestFilesCommand.cs:line 55
   at WixToolset.Core.HarvestFilesCommand.Execute() in D:\a\wix\wix\src\wix\WixToolset.Core\HarvestFilesCommand.cs:line 37
   at WixToolset.Core.Optimizer.Optimize(IOptimizeContext context) in D:\a\wix\wix\src\wix\WixToolset.Core\Optimizer.cs:line 33
   at WixToolset.Core.CommandLine.BuildCommand.OptimizePhase(IReadOnlyCollection`1 intermediates, IReadOnlyCollection`1 localizations, IReadOnlyCollection`1 bindPaths, Dictionary`2 bindVariables, CancellationToken cancellationToken) in D:\a\wix\wix\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 223
   at WixToolset.Core.CommandLine.BuildCommand.ExecuteAsync(CancellationToken cancellationToken) in D:\a\wix\wix\src\wix\WixToolset.Core\CommandLine\BuildCommand.cs:line 116
   at WixToolset.Tools.Program.Run(IServiceProvider serviceProvider, IMessageListener listener, String[] args, CancellationToken cancellationToken) in D:\a\wix\wix\src\wix\wix\Program.cs:line 103
   at WixToolset.Tools.Program.<Main>d__0.MoveNext()
```
