### ISSUE TITLE
Unable to install the Wix Toolset extension on Visual Studio 2019

### ISSUE THREAD

**Issue by sgtnuggets** [wixtoolset/issues#8592]
### WiX Version

1.0.0.22

### .NET or MSBuild or Visual Studio Version

Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework

### HeatWave Version

na

### Windows Version

Server 2019 17763.1999

### Repro Steps

1. Install Visual Studio Enterprise 2019
2. open Manage Extensions
3. Search for Wix Toolset and select Wix v3 - Visual Studio 2019 Extension
4. Click on Install.
5. Exit Visual Studio to trigger the install of the vsix

### Actual Result

getting this error in the logs:
6/24/2024 2:01:51 PM - Scheduling without hotload: No hotloadable VSIX packages were present in the plan
6/24/2024 2:01:53 PM - WebClientEngine failed attempting to download https://az837173.vo.msecnd.net/azcopy-6-2-0/MicrosoftAzureStorageTools.msi from 72.21.81.200.
6/24/2024 2:02:38 PM - Package 'Microsoft.Azure.Storage.AzCopy.Msi,version=6.2.0.35' failed to download from 'https://az837173.vo.msecnd.net/azcopy-6-2-0/MicrosoftAzureStorageTools.msi'. WebClient download failed: The remote server returned an error: (404) Not Found.. Bits download failed: Error context: BG_ERROR_CONTEXT_REMOTE_FILE, Error code: -2145844844. WinInet download failed: Function: HttpQueryInfo-ResponseCode, HR: -2147024492, Message: Url 'https://az837173.vo.msecnd.net/azcopy-6-2-0/MicrosoftAzureStorageTools.msi', Signature: PackageId=Microsoft.Azure.Storage.AzCopy.Msi;PackageAction=DownloadPackage;ReturnCode=0x80131500
6/24/2024 2:02:38 PM - Skipping Install of 'Microsoft.Azure.Storage.AzCopy.Msi,version=6.2.0.35' since the package or a parent package had a vital failure.
6/24/2024 2:02:38 PM - Skipping cache of package 'Microsoft.Azure.Storage.AzCopy.Msi,version=6.2.0.35' since the package or a parent package had a vital failure.
6/24/2024 2:02:38 PM - Skipping cache of package 'Microsoft.VisualStudio.Component.Azure.Storage.AzCopy,version=16.0.28517.75' since the package or a parent package had a vital failure.
6/24/2024 2:03:49 PM - Install Error : System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.Azure.Storage.AzCopy.Msi' failed to download
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install()
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extensionToInstall, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
---> (Inner Exception #0) Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.Azure.Storage.AzCopy.Msi' failed to download
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

### Expected Result

A successful install of the extension with no error messages. Interestingly, when I re-launch visual studio, the extension shows as installed. Not sure if it's actually working though. 

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Looks like a problem with Microsoft.Azure.Storage.AzCopy.Msi, not WiX.

**Comment by sgtnuggets** [comment]
Yep, the error is because the installer (or something) is trying to download a very outdated version of azCopy, and MS pulled the rug from that old version. Is azCopy part of the wix toolset installer?

**Comment by barnson** [comment]
No.

**Comment by sgtnuggets** [comment]
My bad, it was a red herring. Real issue here: https://developercommunity.visualstudio.com/t/PackageId:MicrosoftAzureStorageAzCopy/10679936?q=MicrosoftAzureStorageTools.msi

Closing the issue.
